server:
 port: 8081

spring:
  application:
    name: account_api

  datasource:
# MySQL ?? URL (DB ??, ???, ??? ??)
    url: jdbc:mysql://10.116.64.14:13306/nhn_academy_6?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
# MySQL ?? ??
    username: nhn_academy_6
# MySQL ?? ????
    password: p63Amk!F0Mgvrd3&
# ???? ??? ??
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto : create
    show-sql: true
    properties:
      hibernate:
        format_sql: true